version: '3.8'

services:
  db:
    container_name: sql_day12
    build:
      context: .
      dockerfile: src/Dockerfile
    volumes:
      - ./materials/rush01_model.sql:/docker-entrypoint-initdb.d/00_rush01_model.sql
      - ./src:/home/src
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: base
    ports:
      - "5432:5432"
