version: '3.8'

services:
  db:
    container_name: sql_day6
    build:
      context: .
      dockerfile: src/Dockerfile
    volumes:
      - ./src/ex00/team00_ex00.sql:/docker-entrypoint-initdb.d/team00_ex00.sql
      - ./src:/home/src
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: base
    ports:
      - "5432:5432"
